version: 2.1

orbs:
  plugin-ci: mattermost/plugin-ci@volatile

jobs:
  build-aws-lambda:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: Building App bundle for Mattermost Cloud
          command: make dist-cloud dist-aws
      - persist_to_workspace:
          root: dist
          paths:
            - "*.zip"
      - store_artifacts:
          path: dist

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - plugin-ci/lint
      - plugin-ci/test
      - plugin-ci/build
      - build-aws-lambda

  ci:
    jobs:
      - build-aws-lambda:
          filters:
            tags:
              only: /^v.*/
      - plugin-ci/lint:
          filters:
            tags:
              only: /^v.*/
      - plugin-ci/test:
          filters:
            tags:
              only: /^v.*/
      - plugin-ci/coverage:
          filters:
            tags:
              only: /^v.*/
          requires:
            - plugin-ci/test
      - plugin-ci/build:
          filters:
            tags:
              only: /^v.*/
          requires:
            - plugin-ci/test
      - plugin-ci/deploy-ci:
          filters:
            branches:
              only: master
          context: plugin-ci
          requires:
            - plugin-ci/lint
            - plugin-ci/coverage
            - plugin-ci/build
            - plugin-ci/test
      - plugin-ci/deploy-release-github:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          context: matterbuild-github-token
          requires:
            - plugin-ci/lint
            - plugin-ci/coverage
            - plugin-ci/build
            - plugin-ci/test
