version: 2.1

orbs:
  plugin-ci: mattermost/plugin-ci@volatile

jobs:
  build:
    executor:
      name: plugin-ci/default
    steps:
      - checkout
      - run:
          name: Building App bundled as plugin
          command: make dist
      - run:
          name: Building App bundled as AWS
          command: make dist-aws
      - run:
          name: Generating Release Notes
          command: >
            printf "Supported Mattermost Server Versions: **$(cat plugin.json | jq
            .min_server_version -r)+** \n## Enhancements\n\n## Fixes\n"  >>
            dist/release-notes.md

            if [[ $(git tag -l | wc -l) -eq 1 ]]; then
              git log --pretty='format:- %h %s' --abbrev-commit --no-decorate --no-color $(git rev-list --max-parents=0 HEAD) HEAD >> dist/release-notes.md
            else
              git log --pretty='format:- %h %s' --abbrev-commit --no-decorate --no-color $(git describe --tags --abbrev=0 $(git describe --tags --abbrev=0)^)..HEAD >> dist/release-notes.md
            fi
      - persist_to_workspace:
          root: dist
          paths:
            - "*.zip"
            - '*.tar.gz'
            - release-notes.md
      - store_artifacts:
          path: dist

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - plugin-ci/lint
      - plugin-ci/test
      - build

  ci:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
          requires:
            - plugin-ci/test
      - plugin-ci/lint:
          filters:
            tags:
              only: /^v.*/
      - plugin-ci/test:
          filters:
            tags:
              only: /^v.*/
      - plugin-ci/coverage:
          filters:
            tags:
              only: /^v.*/
          requires:
            - plugin-ci/test
      - plugin-ci/deploy-ci:
          filters:
            branches:
              only: master
          context: plugin-ci
          requires:
            - plugin-ci/lint
            - plugin-ci/coverage
            - build
            - plugin-ci/test
      - plugin-ci/deploy-release-github:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          context: matterbuild-github-token
          requires:
            - plugin-ci/lint
            - plugin-ci/coverage
            - build
            - plugin-ci/test
